name: net_watcher_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  device_info_plus: ^11.4.0
  network_info_plus: ^6.1.4
  serverpod_client: 2.6.0
