x-postgres-common: 
  &postgres-common
  image: postgres:15
  restart: unless-stopped

services:
  postgres-master:
    <<: *postgres-common
    container_name: net_watcher_db_master
    env_file:
      - master_bd.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/master_bd:/var/lib/postgresql/data
      - ./scripts/01_init_netwatcher.sh:/docker-entrypoint-initdb.d/01_init_netwatcher.sh
      - ./scripts/02_init_base.sql:/scripts/02_init_base.sql
      - ./scripts/03_init_schema.sql:/scripts/03_init_schema.sql
      - ./config/master:/etc/postgresql_custom    
    networks:
      - netwatcher
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql_custom/postgresql.conf -c hba_file=/etc/postgresql_custom/pg_hba.conf

  postgres_replica:
    <<: *postgres-common
    container_name: net_watcher_db_slave
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGUSER: replicator
      PGPASSWORD: replicator_password
      POSTGRES_DB: postgres
    volumes:
      - ./data/slave_bd:/var/lib/postgresql/data
      - ./scripts/slave_entrypoint.sh:/docker-entrypoint-initdb.d/slave_entrypoint.sh
    networks:
      - netwatcher
    depends_on:
      postgres-master:
        condition: service_healthy

networks:
  netwatcher:
    driver: bridge
