services:

  nginx1:
    build: ./net_watcher_web
    container_name: net_watcher_web_1
    ports:
      - "8081:80"
    environment:
      PORT: 80
      ROOT_DIR: "/usr/share/nginx/html"
      SERVER_NAME: web.netwatcher.com

  nginx2:
    build: ./net_watcher_web
    container_name: net_watcher_web_2
    ports:
      - "8082:80"
    environment:
      PORT: 80
      ROOT_DIR: "/usr/share/nginx/html"
      SERVER_NAME: web2.netwatcher.com